### ISSUE TITLE
Report pages 404

### ISSUE THREAD

**Issue by schneidmaster** [schneidmaster/gitreports.com#97]
Submitter: Christian Haschek
Email: christian.haschek@gmail.com
Hello! I have created a gitreport repo a few months ago without problems but I recently tried to create two more and I can change all settings but when I click the "Public URL" link I always get a 404 for all new repositories. Link: https://gitreports.com/issue/chrisiaut/brg1

Am I missing something or is it limited to one repo on this hosted site?

Best regards,
Chris

**Comment by Mark9870** [comment]
I think found what's causing the problem as i am experiencing the same problem just right now.
**Extra detail that is very important - i am making a git report for a friend's github repo, so i do not own it, i am only a member.**

Now, in https://gitreports.com/repositories/ [some number], the public link goes to https://gitreports.com/issue/Jeremiidesu/osu-rank . This leads to a 404.

After a few minutes, however, i found out that the link in https://gitreports.com/profile is different than the one in the repositories page.

It is https://gitreports.com/issue/Mark9870/osu-rank which then, does not have a 404 and is the form page. If i try to submit a report from there however, it goes to /Jeremiidesu/osu-rank and results in a 404, and thus no report is sent to the repo.

**Comment by vatbub** [comment]
Hey,
same here ([https://gitreports.com/issue/vatbub/zorkClone](https://gitreports.com/issue/vatbub/zorkClone)) but I am actually the repo owner of that repo

**Comment by vatbub** [comment]
Hmm, will anything happen here soon?

**Comment by vatbub** [comment]
ok, I've been digging around the issue now for myself and I found out that the 404 actually comes from the GitHub API, but I still don't know , why

**Comment by schneidmaster** [comment]
I believe this was caused by a GitHub API change -- fixed by upgrading to the latest version of octokit.

**Comment by loehnertz** [comment]
As of today this bug is still existent for me!
I've successfully used Gitreports in the past but I tried to hook up a new repo of mine and I get the same 404 as well (https://gitreports.com/issue/loehnertz/HSRMMedialabTimetableApp).
Was there a change in the GitHub API once again?
Deactivating and re-activating it brings no luck.

**Comment by schneidmaster** [comment]
Sorry to hear you're still having trouble. Feel free to investigate and send a PR!

I will look into it when I can but my schedule is currently very full (and, needless to say, Git Reports is a free service).
